# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models
# Unable to inspect table 'auth_group'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'auth_group_permissions'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'auth_permission'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'conf_setting'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'core_sitepermission'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'core_sitepermission_sites'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'django_admin_log'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'django_comment_flags'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'django_comments'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'django_content_type'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'django_migrations'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'django_redirect'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'django_session'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'django_site'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'generic_assignedkeyword'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'generic_keyword'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'generic_rating'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'generic_threadedcomment'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'managements_adminusers'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'managements_adminusers_groups'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'managements_adminusers_user_permissions'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'managements_usergroup'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'managements_userroles'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'managements_users'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'pages_link'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'pages_page'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'pages_richtextpage'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'udd_ai_dimensions'
# The error was: sequence index must be integer, not 'slice'
