# Generated by Django 2.0.5 on 2019-05-10 15:16

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('founded_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinLengthValidator(4)])),
                ('website', models.URLField(max_length=500)),
                ('employee_count', models.IntegerField(choices=[(1, 'From 1 to 10'), (2, 'From 10 to 50'), (3, 'From 50 to 100'), (4, 'From 100 to 500'), (5, 'From 500 to 1000')], default=1)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('company_info', models.CharField(blank=True, max_length=255, null=True)),
                ('competitors', models.CharField(blank=True, max_length=255, null=True)),
                ('selling_points', models.CharField(blank=True, max_length=255, null=True)),
                ('products', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
