# Generated by Django 2.0.5 on 2019-05-13 18:38

import django.core.validators
from django.db import migrations, models
import recruit_api.apps.client.models.client


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='competitors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='founded_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), recruit_api.apps.client.models.client.RecruitMinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='products',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='selling_points',
            field=models.TextField(blank=True, null=True),
        ),
    ]
