# Generated by Django 2.0.5 on 2019-06-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20190609_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
