# Generated by Django 2.2.3 on 2019-08-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_merge_20190710_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
