# Generated by Django 2.2.3 on 2019-08-09 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0012_auto_20190808_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(1, 'Leads'), (2, 'Submittals'), (3, 'Sendout'), (4, 'Interview'), (5, 'Hired/Placement'), (6, 'Rejected'), (7, 'On Hold'), (8, 'Closed')], default=1),
        ),
    ]
