# Generated by Django 2.0.5 on 2019-10-24 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20190819_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
