# Generated by Django 2.0.5 on 2019-11-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20191024_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.IntegerField(choices=[(1, 'Contact Person'), (2, 'Hiring Manager')], default=1),
        ),
    ]
