# Generated by Django 2.2.6 on 2019-11-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_auto_20191105_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='entitlement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='hierchy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
