# Generated by Django 2.2 on 2020-03-02 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('sender_id', models.CharField(max_length=100)),
                ('receiver_id', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('message_date', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('-message_date',),
            },
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('auth_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_id', models.CharField(max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=200, null=True)),
                ('access_token_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('followers_count', models.IntegerField(default=0)),
                ('friends_count', models.IntegerField(default=0)),
                ('favourites_count', models.IntegerField(default=0)),
                ('account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'pending'), ('ok', 'ok'), ('failed', 'failed')], default='pending', max_length=7)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('tweet_id', models.CharField(max_length=100)),
                ('tweet_date', models.DateTimeField(null=True)),
                ('text', models.TextField(max_length=200)),
                ('media_url', models.CharField(blank=True, default='', max_length=200)),
                ('retweet_count', models.IntegerField(default=0)),
                ('favourite_count', models.IntegerField(default=0)),
                ('is_quote_status', models.BooleanField(default=False)),
                ('retweeted', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.TwitterAccount')),
            ],
            options={
                'ordering': ('-tweet_date',),
            },
        ),
        migrations.CreateModel(
            name='TweetReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('reply_id', models.CharField(max_length=100)),
                ('twitter_id', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('media_url', models.CharField(blank=True, default='', max_length=200)),
                ('reply_date', models.DateTimeField(null=True)),
                ('retweet_count', models.IntegerField(default=0)),
                ('favourite_count', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.TweetReply')),
                ('tweet_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.Tweets')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.TwitterAccount')),
            ],
            options={
                'ordering': ('-reply_date',),
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('twitter_id', models.CharField(max_length=100)),
                ('mention_date', models.DateTimeField(null=True)),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.TweetReply')),
                ('tweet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.Tweets')),
            ],
            options={
                'ordering': ('-mention_date',),
            },
        ),
    ]
