# Generated by Django 2.0.5 on 2019-07-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190709_2304'),
        ('user', '0002_auto_20190709_1445'),
    ]

    operations = [
    ]
