# Generated by Django 2.0.5 on 2019-07-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20190523_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='third_party_bill_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='visa_1099_bill_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
