# Generated by Django 2.0.5 on 2019-07-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20190703_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='third_party_bill_rate',
            field=models.CharField(blank=True, default='1.18', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='visa_1099_bill_rate',
            field=models.CharField(blank=True, default='1.15', max_length=255, null=True),
        ),
    ]
