# Generated by Django 2.0.5 on 2019-07-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20190709_1445'),
        ('job', '0005_auto_20190709_2304'),
    ]

    operations = [
    ]
