# Generated by Django 2.2.3 on 2019-07-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_merge_20190710_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='citizen_bill_rate',
            field=models.CharField(blank=True, default='1.18', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='green_card_bill_rate',
            field=models.CharField(blank=True, default='1.18', max_length=255, null=True),
        ),
    ]
