# Generated by Django 2.2.3 on 2019-08-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, to='job.Skills'),
        ),
    ]
