# Generated by Django 2.0.5 on 2019-10-24 01:19

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_auto_20191021_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HiringPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HiringTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['priority', '-created', 'title'], 'verbose_name_plural': 'Jobs'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='hiring_manager',
        ),
        migrations.AddField(
            model_name='job',
            name='hiring_manager_email',
            field=models.ManyToManyField(blank=True, to='job.HiringEmail'),
        ),
        migrations.AddField(
            model_name='job',
            name='hiring_manager_phone',
            field=models.ManyToManyField(blank=True, to='job.HiringPhone'),
        ),
        migrations.AddField(
            model_name='job',
            name='hiring_manager_title',
            field=models.ManyToManyField(blank=True, to='job.HiringTitle'),
        ),
    ]
