# Generated by Django 2.0.5 on 2019-10-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0049_hiringmanageremail_hiringmanagerphone_hiringmanagertitle'),
        ('job', '0018_auto_20191024_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ManyToManyField(blank=True, to='candidate.HiringManagerEmail')),
                ('phone', models.ManyToManyField(blank=True, to='candidate.HiringManagerPhone')),
                ('title', models.ManyToManyField(blank=True, to='candidate.HiringManagerTitle')),
            ],
            options={
                'verbose_name': 'HiringManager',
                'verbose_name_plural': 'HiringManagers',
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='hiring_manager_email',
        ),
        migrations.RemoveField(
            model_name='job',
            name='hiring_manager_phone',
        ),
        migrations.RemoveField(
            model_name='job',
            name='hiring_manager_title',
        ),
        migrations.DeleteModel(
            name='HiringEmail',
        ),
        migrations.DeleteModel(
            name='HiringPhone',
        ),
        migrations.DeleteModel(
            name='HiringTitle',
        ),
        migrations.AddField(
            model_name='job',
            name='hiringmanager',
            field=models.ManyToManyField(blank=True, to='job.HiringManager'),
        ),
    ]
