# Generated by Django 2.0.5 on 2019-11-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_auto_20191030_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
