# Generated by Django 2.2.6 on 2019-11-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_add_extra_fields_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='modified',
            field=models.DateField(blank=True, null=True),
        ),
    ]
