# Generated by Django 2.0.5 on 2019-11-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_add_created_modified_fields_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
    ]
