COUNTRY_CODE = {
    "AD": "Andorra",
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AG": "Antigua & Barbuda",
    "AI": "Anguilla",
    "AL": "Albania",
    "AM": "Armenia",
    "AN": "Netherlands Antilles",
    "AO": "Angola",
    "AQ": "Antarctica",
    "AR": "Argentina",
    "AS": "American Samoa",
    "AT": "Austria",
    "AU": "Australia",
    "AW": "Aruba",
    "AZ": "Azerbaijan",
    "BA": "Bosnia and Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BH": "Bahrain",
    "BI": "Burundi",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BN": "Brunei Darussalam",
    "BO": "Bolivia",
    "BR": "Brazil",
    "BS": "Bahama",
    "BT": "Bhutan",
    "BU": "Burma (no longer exists)",
    "BV": "Bouvet Island",
    "BW": "Botswana",
    "BY": "Belarus",
    "BZ": "Belize",
    "CA": "Canada",
    "CC": "Cocos (Keeling) Islands",
    "CF": "Central African Republic",
    "CG": "Congo",
    "CH": "Switzerland",
    "CI": "Côte D'ivoire (Ivory Coast)",
    "CK": "Cook Iislands",
    "CL": "Chile",
    "CM": "Cameroon",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CS": "Czechoslovakia (no longer exists)",
    "CU": "Cuba",
    "CV": "Cape Verde",
    "CX": "Christmas Island",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DD": "German Democratic Republic (no longer exists)",
    "DE": "Germany",
    "DJ": "Djibouti",
    "DK": "Denmark",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "DZ": "Algeria",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "EH": "Western Sahara",
    "ER": "Eritrea",
    "ES": "Spain",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FJ": "Fiji",
    "FK": "Falkland Islands (Malvinas)",
    "FM": "Micronesia",
    "FO": "Faroe Islands",
    "FR": "France",
    "FX": "France, Metropolitan",
    "GA": "Gabon",
    "GB": "United Kingdom (Great Britain)",
    "GD": "Grenada",
    "GE": "Georgia",
    "GF": "French Guiana",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Greenland",
    "GM": "Gambia",
    "GN": "Guinea",
    "GP": "Guadeloupe",
    "GQ": "Equatorial Guinea",
    "GR": "Greece",
    "GS": "South Georgia and the South Sandwich Islands",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HK": "Hong Kong",
    "HM": "Heard & McDonald Islands",
    "HN": "Honduras",
    "HR": "Croatia",
    "HT": "Haiti",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IN": "India",
    "IO": "British Indian Ocean Territory",
    "IQ": "Iraq",
    "IR": "Islamic Republic of Iran",
    "IS": "Iceland",
    "IT": "Italy",
    "JM": "Jamaica",
    "JO": "Jordan",
    "JP": "Japan",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KH": "Cambodia",
    "KI": "Kiribati",
    "KM": "Comoros",
    "KN": "St. Kitts and Nevis",
    "KP": "Korea, Democratic People's Republic of",
    "KR": "Korea, Republic of",
    "KW": "Kuwait",
    "KY": "Cayman Islands",
    "KZ": "Kazakhstan",
    "LA": "Lao People's Democratic Republic",
    "LB": "Lebanon",
    "LC": "Saint Lucia",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "LY": "Libyan Arab Jamahiriya",
    "MA": "Morocco",
    "MC": "Monaco",
    "MD": "Moldova, Republic of",
    "MG": "Madagascar",
    "MH": "Marshall Islands",
    "ML": "Mali",
    "MN": "Mongolia",
    "MM": "Myanmar",
    "MO": "Macau",
    "MP": "Northern Mariana Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MS": "Monserrat",
    "MT": "Malta",
    "MU": "Mauritius",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NC": "New Caledonia",
    "NE": "Niger",
    "NF": "Norfolk Island",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Netherlands",
    "NO": "Norway",
    "NP": "Nepal",
    "NR": "Nauru",
    "NT": "Neutral Zone (no longer exists)",
    "NU": "Niue",
    "NZ": "New Zealand",
    "OM": "Oman",
    "PA": "Panama",
    "PE": "Peru",
    "PF": "French Polynesia",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PM": "St. Pierre & Miquelon",
    "PN": "Pitcairn",
    "PR": "Puerto Rico",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguay",
    "QA": "Qatar",
    "RE": "Réunion",
    "RO": "Romania",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "SA": "Saudi Arabia",
    "SB": "Solomon Islands",
    "SC": "Seychelles",
    "SD": "Sudan",
    "SE": "Sweden",
    "SG": "Singapore",
    "SH": "St. Helena",
    "SI": "Slovenia",
    "SJ": "Svalbard & Jan Mayen Islands",
    "SK": "Slovakia",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somalia",
    "SR": "Suriname",
    "ST": "Sao Tome & Principe",
    "SU": "Union of Soviet Socialist Republics (no longer exists)",
    "SV": "El Salvador",
    "SY": "Syrian Arab Republic",
    "SZ": "Swaziland",
    "TC": "Turks & Caicos Islands",
    "TD": "Chad",
    "TF": "French Southern Territories",
    "TG": "Togo",
    "TH": "Thailand",
    "TJ": "Tajikistan",
    "TK": "Tokelau",
    "TM": "Turkmenistan",
    "TN": "Tunisia",
    "TO": "Tonga",
    "TP": "East Timor",
    "TR": "Turkey",
    "TT": "Trinidad & Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwan, Province of China",
    "TZ": "Tanzania, United Republic of",
    "UA": "Ukraine",
    "UG": "Uganda",
    "UM": "United States Minor Outlying Islands",
    "US": "United States of America",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VA": "Vatican City State (Holy See)",
    "VC": "St. Vincent & the Grenadines",
    "VE": "Venezuela",
    "VG": "British Virgin Islands",
    "VI": "United States Virgin Islands",
    "VN": "Viet Nam",
    "VU": "Vanuatu",
    "WF": "Wallis & Futuna Islands",
    "WS": "Samoa",
    "YD": "Democratic Yemen (no longer exists)",
    "YE": "Yemen",
    "YT": "Mayotte",
    "YU": "Yugoslavia",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZR": "Zaire",
    "ZW": "Zimbabwe",
    "ZZ": "Unknown or unspecified country",
}

LANG_CODE = {
    "af_ZA": "Afrikaans",
    "gn_PY": "Guaraní",
    "ay_BO": "Aymara",
    "az_AZ": "Azeri",
    "id_ID": "Indonesian",
    "ms_MY": "Malay",
    "jv_ID": "Javanese",
    "bs_BA": "Bosnian",
    "ca_ES": "Catalan",
    "cs_CZ": "Czech",
    "ck_US": "Cherokee",
    "cy_GB": "Welsh",
    "da_DK": "Danish",
    "se_NO": "Northern Sámi",
    "de_DE": "German",
    "et_EE": "Estonian",
    "en_IN": "English (India)",
    "en_PI": "English (Pirate)",
    "en_GB": "English (UK)",
    "en_UD": "English (Upside Down)",
    "en_US": "English (US)",
    "es_LA": "Spanish",
    "es_CL": "Spanish (Chile)",
    "es_CO": "Spanish (Colombia)",
    "es_ES": "Spanish (Spain)",
    "es_MX": "Spanish (Mexico)",
    "es_VE": "Spanish (Venezuela)",
    "eo_EO": "Esperanto",
    "eu_ES": "Basque",
    "tl_PH": "Filipino",
    "fo_FO": "Faroese",
    "fr_FR": "French (France)",
    "fr_CA": "French (Canada)",
    "fy_NL": "Frisian",
    "ga_IE": "Irish",
    "gl_ES": "Galician",
    "ko_KR": "Korean",
    "hr_HR": "Croatian",
    "xh_ZA": "Xhosa",
    "zu_ZA": "Zulu",
    "is_IS": "Icelandic",
    "it_IT": "Italian",
    "ka_GE": "Georgian",
    "sw_KE": "Swahili",
    "tl_ST": "Klingon",
    "ku_TR": "Kurdish",
    "lv_LV": "Latvian",
    "fb_LT": "Leet Speak",
    "lt_LT": "Lithuanian",
    "li_NL": "Limburgish",
    "la_VA": "Latin",
    "hu_HU": "Hungarian",
    "mg_MG": "Malagasy",
    "mt_MT": "Maltese",
    "nl_NL": "Dutch",
    "nl_BE": "Dutch (België)",
    "ja_JP": "Japanese",
    "nb_NO": "Norwegian (bokmal)",
    "nn_NO": "Norwegian (nynorsk)",
    "uz_UZ": "Uzbek",
    "pl_PL": "Polish",
    "pt_BR": "Portuguese (Brazil)",
    "pt_PT": "Portuguese (Portugal)",
    "qu_PE": "Quechua",
    "ro_RO": "Romanian",
    "rm_CH": "Romansh",
    "ru_RU": "Russian",
    "sq_AL": "Albanian",
    "sk_SK": "Slovak",
    "sl_SI": "Slovenian",
    "so_SO": "Somali",
    "fi_FI": "Finnish",
    "sv_SE": "Swedish",
    "th_TH": "Thai",
    "vi_VN": "Vietnamese",
    "tr_TR": "Turkish",
    "zh_CN": "Simplified Chinese (China)",
    "zh_TW": "Traditional Chinese (Taiwan)",
    "zh_HK": "Traditional Chinese (Hong Kong)",
    "el_GR": "Greek",
    "gx_GR": "Classical Greek",
    "be_BY": "Belarusian",
    "bg_BG": "Bulgarian",
    "kk_KZ": "Kazakh",
    "mk_MK": "Macedonian",
    "mn_MN": "Mongolian",
    "sr_RS": "Serbian",
    "tt_RU": "Tatar",
    "tg_TJ": "Tajik",
    "uk_UA": "Ukrainian",
    "hy_AM": "Armenian",
    "yi_DE": "Yiddish",
    "he_IL": "Hebrew",
    "ur_PK": "Urdu",
    "ar_AR": "Arabic",
    "ps_AF": "Pashto",
    "fa_IR": "Persian",
    "sy_SY": "Syriac",
    "ne_NP": "Nepali",
    "mr_IN": "Marathi",
    "sa_IN": "Sanskrit",
    "hi_IN": "Hindi",
    "bn_IN": "Bengali",
    "pa_IN": "Punjabi",
    "gu_IN": "Gujarati",
    "ta_IN": "Tamil",
    "te_IN": "Telugu",
    "kn_IN": "Kannada",
    "ml_IN": "Malayalam",
    "km_KH": "Khmer",
}
