# Generated by Django 2.0.5 on 2019-05-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidate_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.IntegerField(choices=[(1, 'Leads'), (2, 'Submittals'), (3, 'Sendout'), (4, 'Interview'), (5, 'Hired'), (6, 'Rejected')], default=1),
        ),
    ]
