# Generated by Django 2.0.5 on 2019-05-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20190501_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
