# Generated by Django 2.0.5 on 2019-05-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidate_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
