# Generated by Django 2.0.5 on 2019-05-10 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('candidate', '0005_candidate_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='job_title',
        ),
        migrations.AddField(
            model_name='candidate',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
    ]
