# Generated by Django 2.0.5 on 2019-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidate_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='linkedin_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
