# Generated by Django 2.0.5 on 2019-05-14 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_candidate_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
