# Generated by Django 2.0.5 on 2019-05-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_auto_20190514_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='visa_status',
        ),
    ]
