# Generated by Django 2.0.5 on 2019-05-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_remove_candidate_visa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status_visa',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Citizenship'), (3, 'Green Card'), (4, 'Other')], default=2),
        ),
    ]
