# Generated by Django 2.0.5 on 2019-05-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_candidate_status_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='send_signature_html',
            field=models.IntegerField(default=1),
        ),
    ]
