# Generated by Django 2.0.5 on 2019-05-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_candidate_send_signature_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status_visa',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Citizenship'), (3, 'Green Card'), (4, 'HB1 and third party'), (5, 'Other')], default=2),
        ),
    ]
