# Generated by Django 2.0.5 on 2019-05-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_auto_20190527_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
