# Generated by Django 2.0.5 on 2019-06-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0016_auto_20190529_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.IntegerField(choices=[(1, 'Leads'), (2, 'Submittals'), (3, 'Sendout'), (4, 'Interview'), (5, 'Hired'), (6, 'Rejected'), (7, 'Hold'), (8, 'Out Call'), (9, 'Email'), (10, 'Inmail'), (11, 'Waiting for Info'), (12, 'Waiting for Hiring Manager')], default=1),
        ),
    ]
