# Generated by Django 2.0.5 on 2019-06-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0001_initial'),
        ('candidate', '0017_auto_20190609_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_manager.AccountManager'),
        ),
    ]
