# Generated by Django 2.0.5 on 2019-06-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0003_remove_fee_candidate'),
        ('candidate', '0018_candidate_account_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fee_management.Fee'),
        ),
    ]
