# Generated by Django 2.0.5 on 2019-06-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_candidate_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.IntegerField(choices=[(1, 'Leads'), (2, 'Submittals'), (3, 'Sendout'), (4, 'Interview'), (5, 'Hired/Placement'), (6, 'Rejected'), (7, 'On Hold'), (8, 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status_visa',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Citizenship'), (3, 'Green Card'), (4, 'HB1'), (5, '1099'), (6, 'Third Party'), (7, 'Other')], default=2),
        ),
    ]
