# Generated by Django 2.0.5 on 2019-06-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0020_auto_20190617_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='placement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
