# Generated by Django 2.0.5 on 2019-06-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0021_candidate_placement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
