# Generated by Django 2.0.5 on 2019-06-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0022_candidate_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Salary'),
        ),
    ]
