# Generated by Django 2.0.5 on 2019-06-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0023_candidate_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_manager.AccountManager'),
        ),
    ]
