# Generated by Django 2.0.5 on 2019-06-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0027_candidate_third_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='pay_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pay Rate'),
        ),
    ]
