# Generated by Django 2.0.5 on 2019-07-03 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0028_candidate_pay_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekyHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hours_date', models.CharField(blank=True, max_length=55, null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.Candidate')),
            ],
        ),
    ]
