# Generated by Django 2.0.5 on 2019-07-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0030_auto_20190703_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekyhours',
            name='client_paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='weekyhours',
            name='paydate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
