# Generated by Django 2.0.5 on 2019-07-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0031_auto_20190703_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bill_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Bill Rate'),
        ),
    ]
