# Generated by Django 2.0.5 on 2019-07-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0032_candidate_bill_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='start_date',
        ),
        migrations.AddField(
            model_name='candidate',
            name='bill_rate_manual',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
