# Generated by Django 2.0.5 on 2019-07-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0033_auto_20190711_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='bill_rate_manual',
        ),
        migrations.AddField(
            model_name='candidate',
            name='bill_rate_manula',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='manula'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='start_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
