# Generated by Django 2.0.5 on 2019-07-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0034_auto_20190711_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
