# Generated by Django 2.0.5 on 2019-07-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0035_auto_20190715_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
