# Generated by Django 2.0.5 on 2019-07-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0036_auto_20190715_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='start_date',
        ),
    ]
