# Generated by Django 2.0.5 on 2019-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0037_remove_candidate_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
