# Generated by Django 2.0.5 on 2019-07-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0038_candidate_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
