# Generated by Django 2.2.3 on 2019-07-17 04:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0039_auto_20190716_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.Candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
