# Generated by Django 2.2.3 on 2019-07-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0040_userslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslog',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userslog',
            name='rec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
