# Generated by Django 2.2.3 on 2019-07-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0042_auto_20190724_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekyhours',
            name='candidate_paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
