# Generated by Django 2.2.5 on 2019-10-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0045_candidate_total_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
