# Generated by Django 2.2.5 on 2019-10-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0046_candidate_follow_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='follow_up',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
