# Generated by Django 2.0.5 on 2019-10-24 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0047_auto_20191007_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_manager.AccountManager'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Client'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fee_management.Fee'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.Job'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='third_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate.ThirdParty'),
        ),
        migrations.AlterField(
            model_name='userslog',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate.Candidate'),
        ),
        migrations.AlterField(
            model_name='weekyhours',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate.Candidate'),
        ),
    ]
