# Generated by Django 2.0.5 on 2019-12-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0049_hiringmanageremail_hiringmanagerphone_hiringmanagertitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='client_fee',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
