# Generated by Django 2.0.5 on 2020-01-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0051_auto_20200127_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='confirmed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='linkedin_background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='linkedin_education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='linkedin_experience1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='linkedin_experience2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='linkedin_experience3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='linkedin_language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='linkedin_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='withdraw',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
