# Generated by Django 2.1.7 on 2020-03-20 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("reports", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="userreportmapping",
            name="page_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userreportmapping",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_map",
                to="reports.Reports",
            ),
        ),
    ]
