# Generated by Django 2.1.7 on 2020-03-25 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0005_metrics_description"),
        ("reports", "0002_auto_20200320_1100"),
    ]

    operations = [
        migrations.CreateModel(
            name="WidgetTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "style_type",
                    models.CharField(
                        choices=[("line_chart", "line_chart"), ("list", "list")],
                        max_length=50,
                    ),
                ),
                (
                    "metrics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metrics.Metrics",
                    ),
                ),
            ],
            options={"db_table": "report_widget_template"},
        ),
        migrations.AlterUniqueTogether(
            name="userreportmapping", unique_together={("report", "user_id", "page_id")}
        ),
    ]
