# Generated by Django 2.1.7 on 2020-04-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reports", "0003_auto_20200325_0337")]

    operations = [
        migrations.AlterField(
            model_name="reports",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "facebook"),
                    ("instagram", "instagram"),
                    ("linkedin", "linkedin"),
                    ("twitter", "twitter"),
                    ("custom", "custom"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="widgettemplate",
            name="style_type",
            field=models.CharField(
                choices=[
                    ("line_chart", "Line Chart"),
                    ("table_chart", "Table Chart"),
                    ("column", "Column"),
                    ("area", "Area"),
                    ("simple_radial_bar_chart", "Simple Radical Bar Chart"),
                ],
                max_length=50,
            ),
        ),
    ]
