# Generated by Django 2.2 on 2020-04-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200414_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='aggregration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='breakdown',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
