# Generated by Django 2.2 on 2020-04-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20200416_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widget',
            options={'ordering': ('-date_created',)},
        ),
    ]
