# Generated by Django 2.2 on 2020-05-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20200424_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='platform',
            field=models.CharField(blank=True, choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('linkedin', 'linkedin'), ('twitter', 'twitter')], max_length=255, null=True),
        ),
    ]
