# Generated by Django 2.2 on 2020-05-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_widget_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widget',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='widget',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
