# Generated by Django 2.2 on 2020-09-08 14:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0021_auto_20200902_1646'),
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='user_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=64)),
                ('terms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256), default=list, size=None)),
                ('archived_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user_id', models.PositiveIntegerField(db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.Account')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.Board')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
