# Generated by Django 2.2 on 2020-03-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
