# Generated by Django 2.2 on 2020-03-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20200312_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
