# Generated by Django 2.1.7 on 2020-04-06 06:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("metrics", "0005_metrics_description")]

    operations = [
        migrations.AddField(
            model_name="metrics",
            name="fields",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        )
    ]
