# Generated by Django 2.1.7 on 2020-04-13 09:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("metrics", "0006_metrics_fields")]

    operations = [
        migrations.CreateModel(
            name="AccountInbox",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("author", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True)),
                ("date", models.DateTimeField(null=True)),
                (
                    "fields",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AlterUniqueTogether(
            name="account", unique_together={("user_id", "page_id")}
        ),
        migrations.AddField(
            model_name="accountinbox",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="metrics.Account"
            ),
        ),
    ]
