# Generated by Django 2.1.7 on 2020-04-14 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("metrics", "0007_auto_20200413_0923")]

    operations = [
        migrations.CreateModel(
            name="MetricsAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("breakdown", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "aggregration",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "metrics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metrics.Metrics",
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
