# Generated by Django 2.2 on 2020-04-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0008_metricsattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='page_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountobject',
            name='object_type',
            field=models.CharField(choices=[('page', 'page'), ('post', 'post'), ('video', 'video'), ('message', 'message')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='metricsattribute',
            name='breakdown',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
