# Generated by Django 2.2 on 2020-04-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_auto_20200416_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittermention',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('revoked', 'revoked')], max_length=20),
        ),
    ]
