# Generated by Django 2.1.7 on 2020-04-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("metrics", "0010_auto_20200424_1931")]

    operations = [
        migrations.AddField(
            model_name="metricsattribute",
            name="ref_metric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ref_metric_attribute",
                to="metrics.Metrics",
            ),
        )
    ]
