# Generated by Django 2.2 on 2020-04-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0010_auto_20200424_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterreply',
            old_name='description',
            new_name='title',
        ),
    ]
