# Generated by Django 2.2 on 2020-04-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0011_auto_20200428_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterreply',
            old_name='title',
            new_name='description',
        ),
    ]
