# Generated by Django 2.2 on 2020-04-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0011_metricsattribute_ref_metric'),
        ('metrics', '0012_auto_20200428_1410'),
    ]

    operations = [
    ]
