# Generated by Django 2.2 on 2020-05-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0013_merge_20200430_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deleted', 'deleted'), ('revoked', 'revoked')], max_length=20),
        ),
    ]
