# Generated by Django 2.2 on 2020-05-05 08:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0014_auto_20200504_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
