# Generated by Django 2.2 on 2020-05-05 14:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0015_account_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}', null=True),
        ),
    ]
