# Generated by Django 2.2 on 2020-08-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0019_commentreplies_postcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('ok', 'ok'), ('failed', 'failed')], default='pending', max_length=10),
        ),
    ]
