# Generated by Django 2.2 on 2020-09-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0020_auto_20200824_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'pending'), ('progress', 'progress'), ('ok', 'ok'), ('failed', 'failed')], default='pending', max_length=10),
        ),
    ]
