# Generated by Django 2.0.5 on 2019-06-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0002_auto_20190614_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='candidate',
        ),
    ]
