# Generated by Django 2.0.5 on 2019-06-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0003_remove_fee_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='am_commission_percent',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='AM Commission percent'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='client_fee_amount',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Client Fee Amount'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='client_fee_percentage',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Client Fee Percentage'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='rc_commission_percent',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='RC Commission percent'),
        ),
    ]
