# Generated by Django 2.0.5 on 2019-06-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0005_auto_20190617_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='client',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='job',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='recruiter',
        ),
    ]
